server:
  port: 8082
spring:
  application.name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogdb
    username: postgres
    password: admin
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate.jdbc.time_zone: UTC
  flyway.enabled: true
eureka.client.service-url.defaultZone: http://localhost:8761/eureka