server:
  port: 9090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: catalog
          uri: lb://catalog-service
          predicates: [ Path=/catalog/** ]
          filters: [ StripPrefix=1 ]
        - id: order
          uri: lb://order-service
          predicates: [ Path=/order/** ]
          filters: [ StripPrefix=1 ]
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
